USE ROLE ACCOUNTADMIN;

DROP DATABASE AIRBNB;
DROP SCHEMA ECZACK_CAPSTONE.BRONZE;
DROP TABLE ECZACK_CAPSTONE.RAW.BRONZE_ORGANIC_RESULTS;
DROP TABLE ECZACK_CAPSTONE.RAW.RAW_ORGANIC_RESULTS;
DROP TABLE ECZACK_CAPSTONE.RAW.RAW_RESULTS;
DROP STAGE ECZACK_CAPSTONE.RAW.S3_RAW_STAGE;