-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS ECZACK_CAPSTONE_COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE ECZACK_CAPSTONE_COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `eczack` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='password'
  LOGIN_NAME='eczack'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='ECZACK_CAPSTONE_COMPUTE_WH'
  DEFAULT_ROLE='transform'
  DEFAULT_NAMESPACE='ECZACK_CAPSTONE.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE transform to USER dbt;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS ECZACK_CAPSTONE;
CREATE SCHEMA IF NOT EXISTS ECZACK_CAPSTONE.RAW;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE ECZACK_CAPSTONE_COMPUTE_WH TO ROLE transform; 
GRANT ALL ON DATABASE ECZACK_CAPSTONE to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE ECZACK_CAPSTONE to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ECZACK_CAPSTONE to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA ECZACK_CAPSTONE.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECZACK_CAPSTONE.RAW to ROLE transform;
GRANT ALL ON INTEGRATION s3_int TO ROLE transform;
GRANT ALL PRIVILEGES ON TABLE ECZACK_CAPSTONE.RAW.BRONZE_ORGANIC_RESULTS TO ROLE transform;