-- Create a role to contain the Snowpipe privileges
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS snowpipe_s3_role;
GRANT ROLE snowpipe_s3_role TO ROLE ACCOUNTADMIN;

-- Set up permissions to role `snowpipe_s3_role`
GRANT ALL ON WAREHOUSE ECZACK_CAPSTONE_COMPUTE_WH TO ROLE snowpipe_s3_role; 
GRANT ALL ON DATABASE ECZACK_CAPSTONE to ROLE snowpipe_s3_role;
GRANT ALL ON ALL SCHEMAS IN DATABASE ECZACK_CAPSTONE to ROLE snowpipe_s3_role;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ECZACK_CAPSTONE to ROLE snowpipe_s3_role;
GRANT ALL ON ALL TABLES IN SCHEMA ECZACK_CAPSTONE.RAW to ROLE snowpipe_s3_role;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECZACK_CAPSTONE.RAW to ROLE snowpipe_s3_role;
GRANT ALL ON INTEGRATION s3_int TO ROLE snowpipe_s3_role;
GRANT ALL ON STAGE ECZACK_CAPSTONE.RAW.S3_RAW_STAGE TO ROLE snowpipe_s3_role;